[build]
  command = "npm run build:ci"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  EXPORT = "1"
  UNOPTIMIZED = "1"

# 404 处理
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

